- source/community/reactnative/src/components/containers/column.js
- source/community/reactnative/src/components/containers/container-wrapper.js
- source/community/reactnative/src/components/containers/factset.js
- source/community/reactnative/src/components/elements/background-image.js
- source/community/reactnative/src/components/elements/rich-text-block.js
- source/community/reactnative/src/components/inputs/choice-set/choice-set-input.js
- source/community/reactnative/src/components/inputs/input-label.js
- source/community/reactnative/src/components/inputs/input.js
- source/community/reactnative/src/components/inputs/toggle-input.js
- source/community/reactnative/src/models/container-model.js
- source/community/reactnative/src/utils/enums.js
- source/community/reactnative/src/utils/theme-config.js
> Reactnative/release 2.2.9

- source/pic2card/.pylintrc
- source/pic2card/commands/voc2coco.py
- source/pic2card/mystique/ac_export/export_helper.py
- source/pic2card/requirements/requirements-dev.txt
- source/pic2card/tests/test_sample_images.py
- Latest Changes for Pylint check and black check
> Pylint Check and Black check fix

- source/community/reactnative/__test__/__snapshots__/adaptive-card.test.js.snap
- source/community/reactnative/src/components/containers/container-wrapper.js
- source/community/reactnative/src/components/elements/element-wrapper.js
- source/community/reactnative/src/utils/constants.js
- source/community/reactnative/src/visualizer/payloads/data-binding/VerticalContentAlignment_Container.json
- source/community/reactnative/src/visualizer/payloads/data-binding/index.js
- source/community/reactnative/src/visualizer/renderer.js
Reverts BigThinkcode/AdaptiveCards#7
> Revert "Revert "Reactnative/handle vertical content alignment""

- source/community/reactnative/src/components/elements/rich-text-block.js
- source/community/reactnative/src/models/element-model.js
- source/community/reactnative/src/visualizer/payloads/payloads/RichTextBlock.json
Implemented the underline property for the RichTextBlock
> Implemented the underline property for the textRun

- source/community/reactnative/src/components/inputs/input-label.js
- source/community/reactnative/src/components/inputs/input.js
- source/community/reactnative/src/components/inputs/picker-input.js
- source/community/reactnative/src/components/inputs/toggle-input.js
- source/community/reactnative/src/utils/constants.js
Fixed padding issues and other alignment issues for the below `Input` elements.
- Input.Text
- Input.Number
- Input.Date
- Input.Time
- Input.Toggle
> Fixed padding issues and other alignment issues in `Input` elements

- source/community/reactnative/src/components/actions/action-button.js
- source/community/reactnative/src/components/actions/action-wrapper.js
- source/community/reactnative/src/visualizer/payloads/payloads/RichTextBlock.json
Updated the margin and padding for the action items dynamically
Updated the horizontal alignment with the stretch scenario and isEnabled is handled for custom actions
> Updated the margin and padding for the action items dynamically

- source/community/reactnative/src/components/elements/rich-text-block.js
> Removed the underline color

- source/community/reactnative/package.json
- source/community/reactnative/src/components/elements/image.js
> Reactnative/release 2.2.12

- source/community/reactnative/src/components/containers/container-wrapper.js
Applied the container styles in the presence of background image the container.
Compared and verified the functionality with the web platform.
> Updated the container styles

- source/community/reactnative/src/components/containers/column.js
- source/community/reactnative/src/components/inputs/text-input.js
Below issues are fixed: 
-  Input.Text default `value` property is not considered
- Column styling unwanted background color issue.
> Fixed input default value issue and column styling issue

- source/community/reactnative/src/components/actions/action-button.js
- source/community/reactnative/src/components/actions/action-wrapper.js
- source/community/reactnative/src/utils/constants.js
Issues
1. Vertical alignment for actions in Host Config is not working as expected - breaking structure padding and margins when there are multiple actions defined
2. Button spacing not as expected - can be structured in a better way
1. ![btc_actions_after](https://user-images.githubusercontent.com/75725813/143443889-6b132e4c-a737-4ff5-9dcd-f2f271cabaaf.png)
2. ![btc_actions_spacing_after](https://user-images.githubusercontent.com/75725813/143443914-b2bd7775-5c65-455d-889a-bc1557a19bb0.png)
`{
"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
"type": "AdaptiveCard",
"version": "1.3",
"body": [
{
"type": "TextBlock",
"text": "Your registration is almost complete",
"size": "Medium",
"weight": "Bolder"
},
{
"type": "TextBlock",
"text": "What type of food do you prefer?", …
> Fixing Action orientation in vertical state

- source/community/reactnative/src/adaptive-card.js
Whenever payload is updated, the scroll position of the card is retained. This shouldn't be the case as new payload should have it's own starting scenario
https://user-images.githubusercontent.com/75725813/143822359-746b013b-19af-4cf6-883e-5b5bdf629cbb.mov
`{
"type": "AdaptiveCard",
"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
"version": "1.3",
"body": [
{
"type": "TextBlock",
"text": "Input Fields Validation",
"size": "medium",
"weight": "bolder",
"wrap": true
},
{
"type": "Input.Number",
"placeholder": "Non-required number field validation",
"id": "field1",
"label": "Number",
"min": "10",
"errorMessage": "min value 10"
},
{
"type": "Input.Number",
"placeholder": "Default number validation (non-required)",
"id": "field2",
"label": "Default Number (1000000.005)", …
> Scrolling Adaptive card to the top when payload is updated

- source/community/reactnative/package.json
- source/community/reactnative/src/adaptive-card.js
- source/community/reactnative/src/components/actions/action-button.js
- source/community/reactnative/src/components/actions/action-wrapper.js
- source/community/reactnative/src/components/elements/image.js
- source/community/reactnative/src/components/elements/label.js
- source/community/reactnative/src/components/inputs/input.js
- source/community/reactnative/src/utils/constants.js
- source/community/reactnative/src/utils/host-config.js
- source/community/reactnative/src/utils/theme-config.js
> Reactnative/release 2.2.15

- source/community/reactnative/src/adaptive-card.js
- source/community/reactnative/src/components/actions/action-wrapper.js
- source/community/reactnative/src/components/containers/container-wrapper.js
- source/community/reactnative/src/components/containers/container.js
- source/community/reactnative/src/components/elements/image.js
- source/community/reactnative/src/components/elements/rich-text-block.js
- source/community/reactnative/src/components/elements/text-block.js
Fixed the following scenarios
- TextBlock margin issue if placed directly inside AdaptiveCard
- Conatiner Bleed not working as expected
- Image alignment issues when image size is more than layout size
- Parent styles not derived when default style is used
Sample JSON 1
`{
"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
"type": "AdaptiveCard",
"version": "1.0",
"body": [
{
"type": "Container",
"style": "emphasis",
"bleed": true,
"items": [
{
"type": "TextBlock",
"text": "Bleeding container at the top of the card",
"wrap": true
}
]
},
{
"type": "TextBlock",
"text": "Dummy TextBlock"
},
{
"type": "Container",
"style": "emphasis",
"bleed": true,
"items": [
{
"type": "TextBlock",
"text": "Bleeding container in the middle of the card",
"wrap": true
}
]
},
{
"type": …
> Fixing Container bleed and alignment issues

- source/community/reactnative/src/utils/markdown-formatter.js
- source/community/reactnative/src/visualizer/payloads/payloads/TextBlock.NewLines.json
- source/community/reactnative/src/visualizer/payloads/payloads/index.js
This PR 
- Fix bug related to space and new lines inside text block. 
- Adds card consisting text block with single/multiple spaces and single/multiple new lines at start, middle and end.
New card TextBlock.NewLines.json added for validation
New Line | Before  | After
-- | -- | -- 
iOS | <img src="https://user-images.githubusercontent.com/25148603/146183888-866ae654-1bbc-4f77-ae38-5c768923d727.png" alt="[Simulator Screen Shot - iPhone 12 Pro Max - 2021-12-15 at 17 22 12]" width="250"/>  <img src="https://user-images.githubusercontent.com/25148603/146183904-75288ba9-73da-4c69-8d16-1e9ba7d0c078.png" alt="[Simulator Screen Shot - iPhone 12 Pro Max - 2021-12-15 at 17 22 18]" width="250"/>  <img src="https://user-images.githubusercontent.com/25148603/146183920-917f0a85-4ec8-4972-ac33-dff2e55431 …
> Handle new line in textblock

- source/community/reactnative/src/adaptive-card.js
> Updating adaptive-card with support for margin in actions

- source/community/reactnative/__test__/__snapshots__/adaptive-card.test.js.snap
- source/community/reactnative/package.json
- source/community/reactnative/src/adaptive-card.js
- source/community/reactnative/src/components/actions/action-set.js
- source/community/reactnative/src/components/actions/action-wrapper.js
- source/community/reactnative/src/components/actions/select-Action.js
- source/community/reactnative/src/components/containers/columnset.js
- source/community/reactnative/src/components/containers/container-wrapper.js
- source/community/reactnative/src/components/containers/container.js
- source/community/reactnative/src/components/elements/background-image.js
- source/community/reactnative/src/components/elements/element-wrapper.js
- source/community/reactnative/src/components/elements/image.js
- source/community/reactnative/src/components/elements/rich-text-block.js
- source/community/reactnative/src/components/elements/text-block.js
- source/community/reactnative/src/components/inputs/input.js
- source/community/reactnative/src/styles/style-config.js
- source/community/reactnative/src/utils/enums.js
- source/community/reactnative/src/utils/host-config.js
- source/community/reactnative/src/utils/markdown-formatter.js
- source/community/reactnative/src/utils/theme-config.js
- source/community/reactnative/src/visualizer/payloads/payloads/TextBlock.NewLines.json
- source/community/reactnative/src/visualizer/payloads/payloads/index.js
- source/community/reactnative/src/visualizer/renderer.js
Major Release - 2.2.16
Handled the container style and bleed.
> Reactnative/release 2.2.16

- source/community/reactnative/src/adaptive-card.js
> Adding reference to ScrollView

- source/community/reactnative/__test__/__snapshots__/adaptive-card.test.js.snap
- source/community/reactnative/package.json
- source/community/reactnative/src/adaptive-card.js
> Release-2.2.17

- source/community/reactnative/src/components/inputs/choice-set/choice-set-input.js
- source/community/reactnative/src/components/inputs/input.js
- source/community/reactnative/src/utils/theme-config.js
This PR:
- Fixes placeholder value issue for Choice set(compact) style.
- Adds support for placeholder cursor color for input component.
- Fixes border color for input action component when not in focus.
Platform| Before| After 
-|-|-
iOS | <img src="https://user-images.githubusercontent.com/25148603/147232405-d84943d0-a1a4-4efa-af92-cdd72f80c1ae.png" alt="[iOSBefore]" width="200"/> | <img src="https://user-images.githubusercontent.com/25148603/147232429-30438d2e-8732-4bbf-9ffd-a611832e27be.png" alt="[iOSAfter]" width="200"/>
Android | <img src="https://user-images.githubusercontent.com/25148603/147232170-8510e646-1656-4e95-80a2-38c8d4b0412e.png" alt="[AndroidBefore]" width="200"/> | <img src="https://user-images.githubusercontent.com/25148603/147232250-27eb97b0-7526-4c20-b4e9-9be5692e2e16 …
> Fixed placeholder issue for Choice set(compact) style

- source/community/reactnative/package.json
- source/community/reactnative/src/components/actions/action-wrapper.js
- source/community/reactnative/src/components/actions/select-Action.js
- source/community/reactnative/src/components/containers/factset.js
- source/community/reactnative/src/components/elements/background-image.js
- source/community/reactnative/src/components/inputs/choice-set/choice-set-input.js
- source/community/reactnative/src/components/inputs/input.js
- source/community/reactnative/src/styles/style-config.js
- source/community/reactnative/src/utils/enums.js
- source/community/reactnative/src/utils/markdown-formatter.js
- source/community/reactnative/src/utils/theme-config.js
Merging the 2.2.18 features to fork-main
> Reactnative/release 2.2.18

- source/community/reactnative/src/components/elements/background-image.js
Fix issue in background image.
> Fix bg image
